#!/usr/bin/env bash

# Author: sskmy1024y
# Last Modified: 29 Aug 2021.

trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -euo pipefail

# set dotfiles path as default variable
if [ -z "${DOTPATH:-}" ]; then
    DOTPATH=$HOME/.dotfiles; export DOTPATH
fi
CONFPATH=$DOTPATH/config

# load lib script (functions)
. "$DOTPATH"/etc/lib/header.sh

## create symbolic link
echo ""
info "Creating symbolic links..."
if [ ! -d "$HOME/.local/bin" ]; then
  mkdir -p "$HOME"/.local/bin
fi
symlink "$DOTPATH/etc/scripts/deploy" "$HOME/.local/bin/deploy"

# zsh
info "zsh..."
symlink "$CONFPATH/zsh/.zshrc" "$HOME/.zshrc"
if [ ! -d "$HOME/.zsh" ]; then
  mkdir -p "$HOME"/.zsh
fi
wild_symlink "$CONFPATH/zsh/*.zsh" "$HOME/.zsh/"

# ssh
info "ssh .."
if [ ! -d "$HOME/.ssh" ]; then
  mkdir -p "$HOME/.ssh"
  chmod 700 "$HOME"/.ssh
fi
if [ ! -f "$HOME/.ssh/authorized_keys" ]; then
  touch "$HOME"/.ssh/authorized_keys
  chmod 600 "$HOME"/.ssh/authorized_keys
fi
symlink "$CONFPATH/ssh/config" "$HOME/.ssh/config"
symlink "$CONFPATH/ssh/git.conf" "$HOME/.ssh/git.conf"
if [ ! -f "$HOME/.ssh/git_private" ]; then
  ssh-keygen -q -f "$HOME"/.ssh/git_private
  mv "$HOME"/.ssh/git_private.pub "$HOME"/.ssh/git_public
fi

# git
info "git..."
symlink "$CONFPATH/git/.gitconfig" "$HOME/.gitconfig"
symlink "$CONFPATH/git/.gitignore.global" "$HOME/.gitignore.global"
symlink "$CONFPATH/git/.gitmessage" "$HOME/.gitmessage"
symlink "$CONFPATH/git/.czrc" "$HOME/.czrc"
mkdir -p "$HOME"/.git_template/hooks

# tmux
info "tmux..."
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm "$HOME"/.tmux/plugins/tpm
fi
symlink "$CONFPATH/tmux/.tmux.conf" "$HOME/.tmux.conf"
# echo "  please check --> doc/tmux.md"
# shellcheck disable=SC2016
echo '  export PATH="$HOME/.tmux/bin:$PATH"'

# local binary
info "binary..."
# shellcheck disable=SC2016
echo '  export PATH="$HOME/.local/bin:$PATH'
# shellcheck disable=SC2016
echo '  export PATH="/opt/local/bin:/opt/local/sbin:$PATH"'
for i in "$DOTPATH"/bin/*; do
  ln -sf "$i" "$HOME"/.local/bin/
done
echo ""
