#!/usr/bin/env bash

# Author: sskmy1024y
# Last Modified: 02 Jul 2025.

trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -euo pipefail

# set dotfiles path as default variable
if [ -z "${DOTPATH:-}" ]; then
    DOTPATH=$HOME/.dotfiles; export DOTPATH
fi

# load lib script (functions)
. "$DOTPATH"/etc/lib/header.sh


## install packages
info "Development environment building..."

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp
#             until this script has finished
while true
do
    sudo -n true
    sleep 60;
    kill -0 "$$" || exit
done 2>/dev/null &

while IFS= read -r script; do
    bash "$script"
done < <(find "$DOTPATH"/etc/scripts/install.d -name "[0-9][0-9]*.sh" | sort)
