# Brewfile
cask_args appdir: "/Applications"

tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "buo/cask-upgrade"

# third party repo

# dev tools
brew "bat"
brew "binutils"
brew "coreutils"
brew "curl"
brew "gcc"
brew "git"
brew "git-lfs"
brew "jq"
brew "openssl"
brew "tmux"
brew "tree"
brew "zplug"
brew "fzf"
brew "tree"
brew "go"
# Required by deep.d/98_font.sh (Nerd Font patcher / Cica build)
brew "fontforge"

cask "google-cloud-sdk"

# cask apps
cask "docker"

# font
cask "font-meslo-lg-nerd-font"
